flake-list: add chaotic nyx flake
NixOS/nixos-search pull request #803
Opened 2024-06-23 16:56 UTC by JohnRTitor

Nix flake for bleeding-edge and unreleased packages (e.g., mesa_git, telegram_git)
Additonally it provides cachyos linux kernel.

@dasJ @Mic92 friendly ping

2024-06-23 17:39 UTC, PedroHLC commented
Note: I wonder if CI from this repo will work in this flake, since it uses https://github.com/NixOS/nix/pull/8892

2024-06-24 19:07 UTC, JohnRTitor commented
Ah, it's a shame then.

2024-06-24 19:22 UTC, JohnRTitor commented
Re-opened with the hope of adding this if flake schemas feature is added to nix, someday.

2024-06-25 13:36 UTC, Mic92 approved these changes

2024-06-25 13:37 UTC, Mic92 requested changes
CI needs a fix. I was just checking, if I can actually merge stuff in this repository.

2025-03-10 16:34 UTC, raboof commented
Filed #899 for that feature

2025-03-10 20:16 UTC, PedroHLC commented
Hummm, can every output be ignored except `legacyPackages`? We've been complying with the “_default flake-schema_” for 3 months (except for an extra `utils` output). Or any link to a doc/guide on how to run the same evaluation locally for me to see what item is failing?

2025-03-11 08:39 UTC, raboof commented
> any link to a doc/guide on how to run the same evaluation locally for me to see what item is failing?

Added some examples in https://github.com/NixOS/nixos-search/pull/901/files

2025-03-12 13:17 UTC, PedroHLC commented
@raboof the problem here seems to be one of my modules' options has the following:
```
  inherit (options.nixpkgs.config) example type;
```

For some reason, this module gets applied to a system that does not have `options.nixpkgs`.

If I comment this `inherit` (and ignore that I have an option without `example` and `type`) the flake is successfully evaluated.

I can duplicate those two from Nixpkgs' source, and I will, but I wonder if this is something to be fixed here for compatibility as well.

2025-03-12 13:21 UTC, raboof commented
> @raboof the problem here seems to be one of my modules' options has the following:
> 
> ```
>   inherit (options.nixpkgs.config) example type;
> ```
> 
> For some reason, this module gets applied to a system that does not have `options.nixpkgs`.
> 
> If I comment this `inherit` (and ignore that I have an option without `example` and `type`) the flake is successfully evaluated.
> 
> I can duplicate those two from Nixpkgs' source, and I will

Interesting, thanks for digging into this.

> but I wonder if this is something to be fixed here for compatibility as well.

Possibly. If you want to create an issue that might be helpful, but realistically tbh I don't plan on working on this myself.

2025-03-12 13:31 UTC, PedroHLC commented
I deployed the workaround.

It seems to have some cache, so I needed to test it as:
```sh
nix run github:nixos/nixos-search#flake-info -- --json flake github:chaotic-cx/nyx/fade09fee2321ba1b3dfd97d624c329c2bbf8699
```

2025-03-12 13:59 UTC, raboof approved these changes

2025-03-12 13:59 UTC, merged